package com.example.listsinandroid;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.widget.ArrayAdapter;

import com.example.listsinandroid.databinding.ActivityMainBinding;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class MainActivity extends AppCompatActivity {
    ActivityMainBinding binding;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        // Inflating the binding of the view
        binding = ActivityMainBinding.inflate(getLayoutInflater());
        setContentView(binding.getRoot());

        // Setting the title for the activity
        setTitle("List View");

        // Make adapter for the list view
        CoursesAdapter adapter = new CoursesAdapter(this, android.R.layout.simple_list_item_1, courses);

        // Set the adapter to the list view
        binding.list.setAdapter(adapter);
    }

    /**
     * <p>List of different courses</p>
     * It is scraped from <a href="https://www.collegedekho.com/courses/">www.collegedekho.com</a>
     */
    private static final List<String> courses = new ArrayList<>(Arrays.asList(
            "B.Tech - Biochemical Engineering",
            "B.Tech - Textile Engineering",
            "B.Tech - Ceramic Engineering",
            "B.Tech - Instrumentation Engineering",
            "B.Tech - Mechatronics Engineering",
            "B.Tech - Telecommunication Engineering",
            "B.Tech - Automobile Engineering",
            "B.Tech - Production Engineering",
            "B.Tech - Mining Engineering",
            "B.Tech - Genetic Engineering",
            "Masters of Computer Management",
            "Bachelor of Education",
            "Bachelor of Visual Communication",
            "Bachelor of Design",
            "Bachelor of Financial Markets",
            "Bachelor of Science",
            "B.Sc Actuarial Sciences",
            "B.Sc - Agriculture",
            "Acting and Film-making",
            "B.Sc - Anthropology",
            "B.Sc - Electronics",
            "B.Sc - Geology",
            "B.Sc - Horticulture",
            "B.Sc - Microbiology",
            "B.Sc - Zoology",
            "Bachelor of Physical Education",
            "Bachelor of Audiology & Speech Language Pathology",
            "Master of Law",
            "LL.M - Criminal Law",
            "LL.M - Cyber Law",
            "LL.M - International Law",
            "LL.M - Labour Law",
            "Bachelor of Medicine and Bachelor of Surgery",
            "Bachelor of Naturopathy and Yogic Sciences",
            "Bachelor of Optometry",
            "Bachelor of Paramedical Technology",
            "Bachelor of Veterinary Science",
            "Masters of Business Administration",
            "Bachelors of Occupational Therapy",
            "General Nursing and Midwifery",
            "MBA - Technology Management",
            "MBA - Natural Resource Management",
            "B.Sc - Forensic Science",
            "B.Sc - Life Sciences",
            "B.Sc - Genetics",
            "M.Sc - Geoinformatics",
            "MBA - Communication Management",
            "MBA - Environmental Management",
            "MBA - International Business",
            "MBA - Media Management",
            "MBA - Systems Management",
            "MBA - Rural Development Management",
            "MBA - Healthcare & Hospital Management",
            "B.Sc - Statistics",
            "B.Sc - Home Science",
            "B.Sc - Computer Science",
            "Bachelor of Banking & Insurance",
            "MBA - Retail Management",
            "Bachelor of Medical Laboratory Technology",
            "MBA - Logistics and Supply Chain Management",
            "Bachelor of Management Studies",
            "MBA - Sports Management",
            "MBA - Sales Management",
            "Bachelor of Hotel Management & Catering Technology",
            "Bachelor of Business Administration",
            "BA LLB",
            "PGP - Tax Management",
            "Bachelor of Elementary Education",
            "MBA - Materials Management",
            "MBA - Operations Management",
            "B.Sc LLB",
            "Bachelors of Commerce and Bachelor of Legislative Law",
            "BBA LLB",
            "Master of Education",
            "Bachelor of Fine Arts",
            "Bachelor of Multimedia Communication",
            "B.A. - Public Administration",
            "Bachelor of Mass Communication",
            "Bachelor of Mass Media",
            "Basic Training Certificate",
            "Masters in Journalism and Mass Communication",
            "Master of Mass Communication",
            "M.A. - Public Administration",
            "Radio Jockey",
            "Advertising",
            "MBA - Project Management",
            "MBA - Risk Management",
            "MBA - Sustainable Management",
            "Textile Designing",
            "MBA - Customer Relationship Management",
            "M.Sc - Oceanography",
            "Data Management/ Data Analysis",
            "M.Sc - Marine Biology",
            "B.Sc - Biological Sciences",
            "M.Sc - Astrology",
            "Bachelor of Computer Applications",
            "MBA - Industrial Management",
            "MBA - Power Management",
            "MBA - Business Process Management",
            "B.Sc - Environmental Sciences",
            "Master of Arts",
            "MBA - Consultancy Management",
            "Master of Science",
            "Astrophysics",
            "Bachelor of Unani Medicine & Surgery",
            "B.Des - Industrial Design",
            "Bachelor of Journalism & Mass Communication",
            "Bachelor of Ayurveda Medical and Surgery",
            "Bachelor of Fisheries Science",
            "Bachelor of Homeopathic Medicine & Surgery",
            "B.Pharma",
            "B.Sc - Forestry",
            "Master of Computer Applications",
            "Fashion Photography",
            "MBA - Design Management",
            "M.Sc - Information Technology",
            "B.Tech - Civil Engineering",
            "Bachelor of Dental Surgery",
            "Bachelor of Physiotherapy",
            "B.Sc Radiotherapy",
            "Bachelor of Social Work",
            "B.Sc - Medical Laboratory Technology",
            "Bachelor of Fashion Technology",
            "Bachelor of Architecture",
            "B.Tech - Mechanical Engineering",
            "B.Tech Aeronautical Engineering",
            "B.Tech Aerospace Engineering",
            "Web Designing",
            "B.Tech - Electrical Engineering",
            "B.Tech - Marine Engineering",
            "MBA - Hospitality Management",
            "MBA - Agri Business Management",
            "Post Graduate Diploma in Management",
            "Master of Technology",
            "MBA - Finance Management",
            "Interior Designing",
            "Company Secretary",
            "Chartered Financial Analyst",
            "Bachelor of Fashion and Apparel Design",
            "Jewellery Designing",
            "Graphic Designing",
            "Auxiliary Nursing and Midwifery",
            "Master of Fine Arts",
            "Chartered Accountancy",
            "Cyber Security & Ethical Hacking",
            "Animation",
            "Bachelor of Tourism and Management",
            "MBA - Fashion Management",
            "Actuarial Science",
            "B.Com Hons.",
            "Event Management",
            "Bachelor of Law",
            "Bachelor of Library Science",
            "Aviation",
            "Journalism",
            "Pilot Training",
            "Banking",
            "MBA in HR",
            "Nutrition & Dietetics",
            "MBA - Investment Management",
            "B.Tech - Food Processing Technology",
            "B.Tech - Software Engineering",
            "LL.M - Corporate Law",
            "Merchant Navy",
            "B.Tech - Petroleum Engineering",
            "Bachelor of Hotel Management",
            "Archaeology",
            "B.Tech - Material Science and Metallurgical Engineering",
            "Master of Tourism Management",
            "Masters of Tourism Administration",
            "Master of Commerce",
            "Master of Hotel Management",
            "Doctor of Pharmacy",
            "Master of Pharmacy",
            "Masters of Business Economics",
            "Masters of Finance & Control",
            "Master of Business Law",
            "Master of Public Health",
            "Banking Law",
            "Photography",
            "Master of Philosophy",
            "AutoCAD",
            "Master of Financial Management",
            "Bachelor of Accounting & Finance",
            "B.Sc - Biochemistry",
            "Air Hostess/ Cabin Crew Courses",
            "Beautician & Make-up Courses",
            "VFX Courses",
            "Master of Social Work",
            "Diplomate of National Board",
            "Master of Physical Education",
            "Master of Physiotherapy",
            "Master of Prosthetics & Orthotics",
            "Master of Occupational Therapy",
            "Master of Chirurgiae - Super Speciality Course in Surgery/ Surgical Oncology",
            "Computer Hardware Courses",
            "Diploma in Pharmacy",
            "Master of Surgery",
            "Bartending Courses",
            "Fashion Styling",
            "Master of Design",
            "Master of Health/Hospital Administration",
            "Master of Dental Surgery",
            "MBA in Biotechnology",
            "MBA in Pharmaceutical Management",
            "MBA in Construction Management",
            "MBA in Tourism Management",
            "MBA in Foreign Trade",
            "MBA in Statistics",
            "MBA in Airline and Airport Management",
            "MBA in Education Management",
            "MBA in E-Commerce",
            "MBA in Marketing",
            "MBA in Aviation Management",
            "MBA in Business Analytics",
            "MBA - Information Technology",
            "MBA in Entrepreneurship",
            "MBA in Computer Science",
            "Bachelor of Commerce",
            "Bachelor of Engineering",
            "B.Tech in Computer Science",
            "Executive MBA",
            "Bachelor of Company Law",
            "M.Sc in Computer Science",
            "B.Sc in Information Technology",
            "M.A. in English",
            "M.A. in Psychology",
            "Diploma in Nursery Teacher Training",
            "BA in English",
            "Master of Veterinary Science",
            "B.Sc in Physics",
            "B.Sc in Chemistry",
            "B.Sc in Biotechnology",
            "B.A. in Psychology",
            "B.Sc in Psychology",
            "Post Basic B.Sc Nursing",
            "M.Sc in Agriculture",
            "Bachelor of Library and Information Science",
            "B.V. Sc. in Veterinary Surgery & Radiology",
            "M.A. in Economics",
            "M.Sc in Psychology",
            "BBA in Aviation",
            "Biotechnology Engineering",
            "BV. Sc. in Animal Production & Management",
            "LL.B. Honours",
            "B.Tech LL.B.",
            "LL. M in Human Rights",
            "M.Phil in Law",
            "Criminal Law",
            "Civil Law",
            "B.Sc in Nursing",
            "MBA in Corporate Social Responsibility",
            "B.Sc in Visual Communication",
            "B.Plan",
            "Bachelor of Sidhha Medicine and Surgery",
            "MBA in Disaster Management",
            "MBA in Operation Management",
            "Bachelor of Arts in Visual Communication",
            "Master of Planning",
            "Bachelor of Business Studies",
            "Doctor of Medicine",
            "B.Sc. Mathematics",
            "Master of Optometry",
            "Bachelor of Public Health",
            "Master of Architecture",
            "Bachelor of Foreign Trade",
            "M.S. in Ayurveda",
            "MBA in Energy and Environment",
            "M.Sc. Nursing",
            "B.Sc Cardiac Care Technology",
            "Doctorate of Medicine",
            "B.Sc Botany",
            "MD in Anaesthesiology",
            "B.Sc Information Technology",
            "B.Sc Ophthalmic Technology",
            "Bachelor of Visual Arts",
            "Diploma in Special Education",
            "B.Ed in Special Education",
            "Bachelor of Vocational Education",
            "Corporate Law",
            "Master of Fashion Management",
            "BBA+MBA",
            "Master in Fashion Technology",
            "Cyber Law",
            "Furniture Design",
            "Labour Law",
            "Master of Finance and Accounting",
            "Bachelor in Hospital Administration",
            "B.Sc Dialysis Therapy",
            "Administrative Law",
            "Fashion Communication",
            "BBA in Tourism Management",
            "Master of Tourism and Hotel Management",
            "PG Diploma in Hospital Management",
            "Masters in Engineering",
            "B.A. B.Ed",
            "BSc B.Ed",
            "B.Ed in Commerce",
            "Intellectual Property Law",
            "Master of Management Studies",
            "Tax Law",
            "Master of Planning",
            "Bachelor of Sports Management",
            "BCA+MCA",
            "B.Pharm + MBA Integrated",
            "B.Ed in Accountancy",
            "B.A. Sociology",
            "B.A. Philosophy",
            "Business Law",
            "B.Ed Biology",
            "M.Sc Applied Mathematics",
            "BBA in Airport Management",
            "B.Tech Information Technology",
            "Masters in Urban and Rural Planning",
            "BBA in Event Management",
            "B.Sc Visual Communication",
            "Diploma in Elementary Education",
            "B.A. Rural Development",
            "M.Sc Horticulture",
            "Visual Merchandising",
            "MBA - Actuarial Science",
            "B.Ed Special Education",
            "M.A. Rural Development",
            "B.Sc Respiratory Therapy",
            "BBA in Digital Marketing",
            "Industrial Design",
            "B.A. Political Science",
            "B.Sc Nutrition",
            "M.A. Political Science",
            "BBA in Media Management",
            "M.Tech Mining Engineering",
            "M.Sc Zoology",
            "B.A. Astrology",
            "BA in Culinary Arts",
            "M.Tech Computer Science",
            "M.Sc Botany",
            "Bachelor of Catering Technology & Culinary Arts",
            "B.Sc. in Occupational Therapy",
            "B.A. Ancient History",
            "M.Tech Electrical Engineering",
            "M.Sc Microbiology",
            "MBA in Event Management",
            "M.Tech in Civil Engineering",
            "B.A. Education",
            "M.Sc Chemistry",
            "BBA in Marketing",
            "B.A. Bengali",
            "M.Tech in Electronics and Communications Engineering",
            "BBA in Finance",
            "M.Sc Physics",
            "B.A. Telugu",
            "B.Tech Food Technology",
            "BBA Banking and Insurance",
            "M.Sc Food Technology",
            "B.Sc Fashion Design",
            "B.Com Taxation",
            "B.A. Hindi",
            "B.Tech Electronics and Communications Engineering",
            "BBA in Foreign Trade",
            "B.Com in Banking and Insurance",
            "M.Sc Biotechnology",
            "MBA in Data Analytics",
            "B.Sc in Graphic Design",
            "B.Com in Bank Management",
            "B.A. Tamil",
            "B.Tech Plastic Engineering",
            "Gemology",
            "B.Sc. in Neurophysiology Technology",
            "BBA in Hospital Management",
            "BBA in Retail Management",
            "M.Sc Electronics",
            "B.Com in Information Technology",
            "Diploma in Gynaecology and Obstetrics",
            "Bachelor in Business Economics",
            "M.A. History",
            "BBA in International Business",
            "M.Com in Finance",
            "M.Pharm in Pharmaceutics",
            "B.Tech Industrial Engineering",
            "BBA Accounting",
            "B.A. History",
            "M.Sc Environmental Science",
            "B.Sc Interior Design",
            "B.Tech Chemical Engineering",
            "Diploma in Health Inspector",
            "BBA in Information Technology",
            "B.Com Travel and Tourism Management",
            "B.A. Malayalam",
            "B.Sc Biomedical Science",
            "B.Com in Management Studies",
            "B.A. Kannada",
            "BBA in Business Economics",
            "B.Tech Agricultural Engineering",
            "MBA in Interior Design",
            "B.Com in Taxation and Finance",
            "B.Sc Game Designing and Development",
            "M.Tech Chemical Engineering",
            "MBA in Safety Management",
            "B.A. French",
            "Diploma in Physiotherapy",
            "B.Tech Biomedical Engineering/ Technology",
            "B.Sc Immunology",
            "B.Com Economics",
            "Commercial Law",
            "B.Com Co-operation",
            "B.Ed in Physical Science",
            "M.A. International Relations",
            "MBA in Advertising Management",
            "M.Pharm Pharmaceutical Analysis",
            "MMS in Marketing",
            "MBA in Infrastructure Management",
            "M.Sc. in Medical-Surgical Nursing",
            "Ceramic Design",
            "Bachelor of Business Management",
            "M.Sc in Child Health Nursing",
            "BBA in HR",
            "B.Des in Knitwear Design",
            "M.Sc in Maternity Nursing",
            "Post Basic Diploma in Operation Room Nursing",
            "BBA in Sports Management",
            "B.Des in Animation",
            "M.Phil in Nursing",
            "B.Tech Artificial Intelligence",
            "M.Tech Textile Engineering",
            "Diploma in Automobile Engineering",
            "M.Sc in Paediatric Nursing",
            "Master of Applied Management",
            "B.Sc Medical Sociology",
            "Diploma in Jewellery Design",
            "Diploma in Textile Design",
            "Diploma in Dental Hygienist",
            "Certificate Course in Fashion Design",
            "Certificate Course in Interior Design",
            "Diploma in Civil Engineering",
            "Diploma in Mechanical Engineering",
            "B.Tech Data Science",
            "Master of Information Management",
            "Master of International Business",
            "M.Pharm in Pharmacognosy",
            "BA in Graphic Design",
            "Diploma in Apparel Merchandising",
            "MBA in Textile Management",
            "Medical Transcription",
            "MBA in Brand Management",
            "Diploma in Electrical Engineering",
            "MBA in Dairy Management",
            "Diploma in Computer Science Engineering",
            "Post Graduate Diploma in Fashion Designing",
            "Diploma in Engineering",
            "Media Law",
            "B.Pharm Hons.",
            "MBA in Telecom Management",
            "Post Graduate Diploma in Interior Designing",
            "M.A. in Textile Designing",
            "MBA in Oil and Gas Management",
            "Maritime Law",
            "Environmental Law",
            "Certificate in CAD",
            "Diploma in Mining Engineering",
            "Diploma in Chemical Engineering",
            "Diploma in Petroleum Engineering",
            "MBA in Service Management",
            "B.Com Applied Economics",
            "B.Sc in Fashion Technology",
            "Diploma in Textile Engineering",
            "Diploma in Ceramic Engineering",
            "M.Com International Business",
            "Diploma in Plastic Engineering",
            "Diploma in Metallurgical Engineering",
            "Diploma in Agriculture",
            "M.Sc Home Science",
            "B.Pharm Unani",
            "Competition Law",
            "B.Com Business Economics",
            "M.Com in Business Studies",
            "M.Tech in Food Technology",
            "MBA in Public Policy Management",
            "MPT Biomechanics",
            "Diploma in Interior Design",
            "Diploma in Animal husbandry",
            "BBA in Healthcare Management",
            "B.Com Foreign Trade Management",
            "B.Sc in Animation",
            "ITI Course in Pump Operator cum Mechanic",
            "ITI Course in Diesel Mechanic",
            "B.Com E-Commerce",
            "ITI Course/Trade in Fitter",
            "MBA in Capital Markets",
            "ITI Course/Trade in Mechanic Motor Vehicle",
            "Fashion Illustration",
            "ITI Course/Trade in Refrigeration and Air Conditioning",
            "ITI Course/Trade in Secretarial Practice",
            "MBA in Hospital Administration",
            "Diploma in Horticulture",
            "M.Pharm Pharmaceutical Biotechnology",
            "Air and Space Law",
            "Post Graduate Program in Management",
            "ITI Course/Trade in Turner",
            "Interaction Design",
            "MBA in Banking and Insurance",
            "Consumer Law",
            "MBA in Digital Marketing",
            "Interior Architecture",
            "B.Com in Sales and Marketing",
            "Integrated M.Sc in Data Science",
            "Transportation Design",
            "Post Graduate Diploma in Hospital and Health Management",
            "Diploma in Dialysis Technician",
            "B.Com in Advanced Accountancy",
            "B.Com in Advertising and Brand Management",
            "Master of Commerce in Statistics",
            "Landscape Design",
            "MBA in Business Law",
            "BA Hons. Economics",
            "Toy Design",
            "Fashion PR",
            "BBA in Risk Management",
            "Exhibition Design",
            "BBA in Industrial Management",
            "MBA in Accounting",
            "Diploma in Anaesthesia",
            "Fashion Journalism",
            "M.Pharm in Clinical Practice and Research",
            "Diploma in Hearing Language and Speech",
            "BBA in Information Systems Management",
            "Diploma in Banking and Finance",
            "BBA in Business Analytics",
            "PGD in Culinary Arts",
            "M.Com in HR",
            "B.Com in HR Management",
            "Diploma in Nursing Care Assistant",
            "Diploma in Homeopathic Medicine & Surgery",
            "BBA in E-Commerce",
            "Retail Design",
            "Diploma in X-Ray Technology",
            "PGD in Travel and Tourism Management",
            "B. Voc in Hotel Management",
            "M.Tech Data Science",
            "Garment Technology",
            "B.Sc. Nuclear Medicine Technology",
            "BBA in Computer Application",
            "M.Pharm Industrial Pharmacy",
            "B.Sc Sericulture",
            "MBA in Shipping and Logistics",
            "M.Com Computer Applications",
            "BBA in Logistics and Supply Chain Management",
            "M.Tech Geoinformatics",
            "Diploma in Advanced Accounting",
            "Diploma in Ophthalmic Technology",
            "M.Tech Genetic Engineering",
            "PG Diploma in Supply Chain and Logistics Management",
            "Postgraduate Diploma in Bank Management",
            "Diploma in Computerised Accounting",
            "M.Sc Sericulture",
            "M.Sc Organic Chemistry",
            "BSc in Hospitality and Hotel Administration",
            "B.Sc Hons Agri-Business Management",
            "M.Tech Computer Science Engineering",
            "Fashion Marketing",
            "BSc in Culinary Arts",
            "B.Sc Hydrology",
            "M.Sc Hydrology",
            "M.Sc Data Science",
            "Diploma in Naturopathy",
            "BSc in Airlines & Airport Management",
            "B.Sc in Travel & Tourism Management",
            "MSc in Tourism and Hospitality Management",
            "B.Sc Analytical Chemistry",
            "M.Tech in Wireless Communication/ Network",
            "M.Sc Virology",
            "Association of Chartered Certified Accountants",
            "PGD in Hotel Management",
            "PG Diploma in Event Management",
            "PG Diploma in Accommodation Operation and Management",
            "Diploma in Journalism and Mass Communication",
            "MBA in Hotel Management",
            "B.Sc in Yoga",
            "Diploma in Broadcast Journalism",
            "BBA in Hotel Management",
            "MBA in Business Management",
            "MBA in Information System Management",
            "MBA in Air Travel Management",
            "Footwear Design",
            "MBA in Real Estate Management",
            "BBA in Real Estate and Urban Infrastructure",
            "B.Com Vocational",
            "PGD in Taxation",
            "PG Diploma in Media and Mass Communication",
            "B.Sc in Radiology",
            "Diploma in Rural Health Care",
            "Bachelor of Arts in Journalism",
            "Apparel Production",
            "Diploma in Optometry Technology",
            "B.Sc in Physician Assistant",
            "B.Voc. Healthcare Management",
            "M.Tech in Structural Engineering",
            "Diploma in Operation Theatre Technology",
            "M.Tech in Geo Technical Engineering",
            "PGD in Law",
            "Diploma in Clinical Pathology",
            "Executive PGDM",
            "PGD in Financial Management",
            "Augmented Reality Design",
            "Post Graduate Programme in Human Resource Management",
            "Energy Law",
            "PGDM in International Business",
            "BA Hons Business Economics",
            "PGDM in HRM",
            "PG Diploma in Business Management",
            "M.Sc in Animation",
            "Post Graduate Diploma in Management in Marketing",
            "Bachelor of Textile",
            "M.Sc in Medical Laboratory Technology",
            "PG Diploma in Textile Design",
            "BBA in Materials Management",
            "MA in Travel and Tourism",
            "PGDM in Operations Management",
            "Diploma in Graphic Design",
            "Post Graduate Diploma in Graphic Design",
            "B.A. Interior Design",
            "PGDM in Business Analytics",
            "B.Sc in Animation and Multimedia",
            "Post Graduate Programme in Agri-Business Management",
            "M.Sc Textile Design",
            "M.Sc Interior Design",
            "Post Graduate Programme in Enterprise Management",
            "B.Sc in Physiotherapy",
            "BBM International Business",
            "Post Graduate Programme in Business Management",
            "Post Graduate Diploma in Corporate Law",
            "BSc in Physiology",
            "BBM in Human Resource Management",
            "B.Sc in Critical Care Technology",
            "PG Diploma in Human Rights Law",
            "Post Graduate Diploma in Cyber Law",
            "Diploma in Dietetics",
            "Doctor of Philosophy",
            "Diploma in Architecture",
            "Master of Arts in Archaeology",
            "Masters of Technology in Biotechnology",
            "Bachelor of Technology in Railway Engineering",
            "Fares & Ticketing",
            "Masters of Technology in Cyber Security",
            "Masters of Technology in Information Technology",
            "Masters of Technology Mechanical Engineering",
            "Masters of Technology Environmental Technology",
            "Bachelor of Technology Thermal Engineering",
            "Bachelor of Technology Dairy Technology"
    ));
}